version: '3.9'

services:
  mysql:
    build:
      context: mysql
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: ${SERVICE_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./datas/databases/mysql/datas:/var/lib/mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    networks:
      - service-network
  php:
    build:
      context: php
      args:
        TIMEZONE: ${TIMEZONE}
        PHP_IMG_VERSION: ${PHP_IMG_VERSION}
    container_name: ${SERVICE_NAME}-php
    networks:
      - service-network

  apache2:
    build:
      context: apache2
    container_name: ${SERVICE_NAME}-apache
    ports:
      - ${APACHE_LOCAL_PORT}:80
    volumes:
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./datas/logs/apache2:/var/log/apache2
    networks:
      - service-network
#        ipv4_address: 172.18.0.37

  memcached:
    image: ${ARCH}/memcached:${MEMCACHED_IMG_VERSION}
    container_name: ${SERVICE_NAME}-memcached
    networks:
      - service-network

  redis:
    image: ${ARCH}/redis:${REDIS_IMG_VERSION}
    container_name: ${SERVICE_NAME}-redis
    ports:
      - ${REDIS_LOCAL_PORT}:6379
    volumes:
      - ./config/redis.conf:/redis.conf
      - ./datas/databases/redis/datas:/data
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - service-network

  mongodb:
    image: ${ARCH}/mongo:${MONGODB_IMG_VERSION}
    container_name: ${SERVICE_NAME}-mongodb
    ports:
      - ${LOCAL_MONGODB_PORT}:27017
    volumes:
      - ${MONGODB_LOCAL_DATA_DIR}:/datas/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWD}
    networks:
      - service-network

  nginx:
    restart: always
    image: ${ARCH}/nginx:latest
    container_name: ${SERVICE_NAME}-nginx
    ports:
      - ${NGINX_LOCAL_PORT}:80
      - ${NGINX_SSL_LOCAL_PORT}:443
    networks:
      - service-network
    volumes:
      - ./config/nginx/${ENV}.nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/mime.types:/etc/nginx/mime.types
      - ./datas/logs/nginx:/var/log/nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  service-network:
    name: ${SERVICE_NAME}-network
    ipam:
      config:
        - subnet: 172.18.0.0/16