version: '3.9'

services:
  apache2:
    build:
      context: ../apache2
      args:
        FCGI_FILE: ${FCGI_FILE}
        APACHE_USER: ${APACHE_USER}
        APACHE_GROUP: ${APACHE_GROUP}
        SERVICE_PATH: ${SERVICE_PATH}
        SERVICE_HOST: ${SERVICE_HOST}
        SERVICE_NAME: ${SERVICE_NAME}
        APP_MAINTAINER_EMAIL: ${APP_MAINTAINER_EMAIL}
        APP_MAINTAINER_FULL_NAME: ${APP_MAINTAINER_FULL_NAME}
    container_name: ${SERVICE_NAME}-apache2
    ports:
      - ${APACHE_LOCAL_PORT}:80
    volumes:
      - ../datas/logs/apache2:/var/log/apache2
      - ${SERVICE_APP_PATH}:/var/www/${SERVICE_NAME}
    networks:
      service-network:
        aliases:
          - ${SERVICE_HOST}
        ipv4_address: 172.20.0.37
    profiles:
      - all
      - http-server
      - apache2