version: '3.9'

services:
  mysql:
    build:
      context: ../mysql
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: ${SERVICE_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../datas/databases/mysql/datas:/var/lib/mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    networks:
      - service-network
    profiles:
      - all
      - database
      - mysql